#!/bin/bash

TYPE=$1
APIPATH=`echo ${TYPE} | tr '[:upper:]' '[:lower:]'`

APIVERSION=${2:-v1}

APIPATHEXT=${3:-s}
if [ ${APIPATHEXT} == "-" ];then 
	APIPATHEXT=
fi

case ${APIVERSION} in
    "extensions/v1beta1")
        API=/apis/extensions/v1beta1
        ;;
    "v1")
        API=/api/v1
        ;;
    "batch/v1")
        API=/apis/batch/v1
        ;;
    "autoscaling/v1")
        API=/apis/autoscaling/v1
        ;;
    *)
        echo "unknown API"
        exit -4
        ;;
esac

cat <<EOF | gofmt > ${APIPATH}.go
package http

import (
	k8s "github.com/YakLabs/k8s-client"
	"github.com/pkg/errors"
)

type (
	watchEvent${TYPE} struct {
		raw k8s.WatchEvent 
		object *k8s.${TYPE}
	}
)

func (w *watchEvent${TYPE}) Type() k8s.WatchEventType {
	return w.raw.Type 
}

func (w *watchEvent${TYPE}) Object() (*k8s.${TYPE}, error) {
	if w.object != nil {
		return w.object, nil
	}
	if w.raw.Type == k8s.WatchEventTypeError {
		var status k8s.Status 
		if err := w.raw.UnmarshalObject(&status); err != nil {
			return nil, errors.Wrap(err, "failed to decode Status")
		}
		return nil, &status
	}
	var object k8s.${TYPE}
	if err := w.raw.UnmarshalObject(&object); err != nil {
		return nil, errors.Wrap(err, "failed to decode ${TYPE}")
	}
	w.object = &object 
	return &object, nil
}

func ${APIPATH}GeneratePath(namespace, name string) string {
    if namespace == "" && name == "" {
        return "${API}/${APIPATH}${APIPATHEXT}"
    }
    if name == "" {
        return "${API}/namespaces/"+namespace+"/${APIPATH}${APIPATHEXT}"
    }
    return "${API}/namespaces/"+namespace+"/${APIPATH}${APIPATHEXT}/"+name
}

// Get${TYPE} fetches a single ${TYPE}
func (c *Client) Get${TYPE}(namespace, name string) (*k8s.${TYPE}, error) {
	var out k8s.${TYPE}
	_, err := c.do("GET", ${APIPATH}GeneratePath(namespace, name), nil, &out)
	if err != nil {
		return nil, errors.Wrap(err, "failed to get ${TYPE}")
	}
	return &out, nil
}

// Create${TYPE} creates a new ${TYPE}. This will fail if it already exists.
func (c *Client) Create${TYPE}(namespace string, item *k8s.${TYPE}) (*k8s.${TYPE}, error) {
	item.TypeMeta.Kind = "${TYPE}"
	item.TypeMeta.APIVersion = "${APIVERSION}"
	item.ObjectMeta.Namespace = namespace

	var out k8s.${TYPE}
	_, err := c.do("POST", ${APIPATH}GeneratePath(namespace, ""), item, &out, 201)
	if err != nil {
		return nil, errors.Wrap(err, "failed to create ${TYPE}")
	}
	return &out, nil
}

// List${TYPE}${APIPATHEXT} lists all ${TYPE}s in a namespace
func (c *Client) List${TYPE}${APIPATHEXT}(namespace string, opts *k8s.ListOptions) (*k8s.${TYPE}List, error) {
	var out k8s.${TYPE}List
	_, err := c.do("GET", ${APIPATH}GeneratePath(namespace, "") + "?"+listOptionsQuery(opts, nil), nil, &out)
	if err != nil {
		return nil, errors.Wrap(err, "failed to list ${TYPE}s")
	}
	return &out, nil
}

// Watch${TYPE}${APIPATHEXT} watches all ${TYPE} changes in a namespace
func (c *Client) Watch${TYPE}${APIPATHEXT}(namespace string, opts *k8s.WatchOptions, events chan k8s.${TYPE}WatchEvent) error {
	if events == nil {
		return errors.New("events must not be nil")
	}
	rawEvents := make(chan k8s.WatchEvent)
	go func() {
		for rawEvent := range rawEvents {
			events <- &watchEvent${TYPE}{raw:rawEvent}
		}
		close(events)
	}()
	_, err := c.doWatch("GET", ${APIPATH}GeneratePath(namespace, "") + "?"+watchOptionsQuery(opts), nil, rawEvents)
	if err != nil {
		return errors.Wrap(err, "failed to watch ${TYPE}s")
	}
	return nil
}

// Delete${TYPE} deletes a single ${TYPE}. It will error if the ${TYPE} does not exist.
func (c *Client) Delete${TYPE}(namespace, name string) error {
	_, err := c.do("DELETE", ${APIPATH}GeneratePath(namespace, name), nil, nil)
	return errors.Wrap(err, "failed to delete ${TYPE}")
}

// Update${TYPE} will update in place a single ${TYPE}. Generally, you should call
// Get and then use that object for updates to ensure resource versions
// avoid update conflicts
func (c *Client) Update${TYPE}(namespace string, item *k8s.${TYPE}) (*k8s.${TYPE}, error) {
	item.TypeMeta.Kind = "${TYPE}"
	item.TypeMeta.APIVersion = "${APIVERSION}"
    item.ObjectMeta.Namespace = namespace

	var out k8s.${TYPE}
	_, err := c.do("PUT", ${APIPATH}GeneratePath(namespace, item.Name), item, &out)
	if err != nil {
		return nil, errors.Wrap(err, "failed to update ${TYPE}")
	}
	return &out, nil
}
EOF
